name: Android Release

on:
  push:
    branches: ["main","feature/add-initial-actions"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.7"
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Run Tests
        run: flutter test

      - name: Start release build
        run: flutter build appbundle
